'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AnswerDetail
    
    '''<summary>
    '''tblDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblDetail As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tdQues control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdQues As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''tdOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdOptions As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''text1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents text1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tdCorrectOption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdCorrectOption As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''text2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents text2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''tdGivenAnswer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tdGivenAnswer As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''text3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents text3 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBack As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''lblTotalMarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalMarks As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMarksObtained control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMarksObtained As Global.System.Web.UI.WebControls.Label
End Class
