'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace unirecruite
    
    Partial Public Class BulkQuestionsInsert
        
        '''<summary>
        '''tbl_feedback control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tbl_feedback As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''MyFile control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents MyFile As Global.System.Web.UI.WebControls.FileUpload
        
        '''<summary>
        '''imgBtnImpData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgBtnImpData As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''imgBtnDetails control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgBtnDetails As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''imgBtnBack control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgBtnBack As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''lblCsvFormat control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblCsvFormat As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''gridDiv control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gridDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''tblrow2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblrow2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''lblSummary control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblSummary As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblTotal control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblTotal As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblInserted control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblInserted As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblDuplicate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblDuplicate As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblMessage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMessage As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''DataGrid1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DataGrid1 As Global.System.Web.UI.WebControls.DataGrid
        
        '''<summary>
        '''tblpages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblpages As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''imgfirst control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgfirst As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''imgprev control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgprev As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''imgnext control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgnext As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''imglast control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imglast As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''ddlPages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlPages As Global.System.Web.UI.WebControls.DropDownList
    End Class
End Namespace
