'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace unirecruite
    
    Partial Public Class CandStatus
        
        '''<summary>
        '''LblMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LblMsg As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''dblCenter control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dblCenter As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''dblCourse control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents dblCourse As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''TxtUserName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TxtUserName As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''ddlStatus control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlStatus As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''ddlgrade control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlgrade As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''TxtFrom control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TxtFrom As Global.System.Web.UI.HtmlControls.HtmlInputText
        
        '''<summary>
        '''TxtTo control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TxtTo As Global.System.Web.UI.HtmlControls.HtmlInputText
        
        '''<summary>
        '''txtAppFromDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtAppFromDate As Global.System.Web.UI.HtmlControls.HtmlInputText
        
        '''<summary>
        '''TxtAppToDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents TxtAppToDate As Global.System.Web.UI.HtmlControls.HtmlInputText
        
        '''<summary>
        '''BtnSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BtnSearch As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnclear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnclear As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnBack control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnBack As Global.System.Web.UI.WebControls.ImageButton
        
        '''<summary>
        '''UpdatePanel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
        
        '''<summary>
        '''ScriptManager1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
        
        '''<summary>
        '''Panel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''lbldate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbldate As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txtnewdate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtnewdate As Global.System.Web.UI.HtmlControls.HtmlInputText
        
        '''<summary>
        '''btnOkay control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnOkay As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnPopUpCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnPopUpCancel As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnCancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCancel As Global.System.Web.UI.HtmlControls.HtmlInputButton
        
        '''<summary>
        '''ModalPopupExtender1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ModalPopupExtender1 As Global.AjaxControlToolkit.ModalPopupExtender
        
        '''<summary>
        '''Panel2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Panel2 As Global.System.Web.UI.WebControls.Panel
        
        '''<summary>
        '''lbldate2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbldate2 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txtReassign control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtReassign As Global.System.Web.UI.HtmlControls.HtmlInputText
        
        '''<summary>
        '''btnOkay2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnOkay2 As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnPopUpCancel2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnPopUpCancel2 As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnCancel2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnCancel2 As Global.System.Web.UI.HtmlControls.HtmlInputButton
        
        '''<summary>
        '''ModalPopupExtender2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ModalPopupExtender2 As Global.AjaxControlToolkit.ModalPopupExtender
        
        '''<summary>
        '''gridDiv control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gridDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''PageSizeList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PageSizeList As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''imgfirst control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgfirst As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''imgprev control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgprev As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''imgnext control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgnext As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''imglast control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imglast As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''LblRecCnt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LblRecCnt As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblRecordCount control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblRecordCount As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''DGReport control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DGReport As Global.System.Web.UI.WebControls.DataGrid
        
        '''<summary>
        '''tblPagebuttons control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblPagebuttons As Global.System.Web.UI.HtmlControls.HtmlTable
        
        '''<summary>
        '''imgBtnDelete control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgBtnDelete As Global.System.Web.UI.WebControls.ImageButton
    End Class
End Namespace
