'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace unirecruite
    
    Partial Public Class changepass
        
        '''<summary>
        '''lbl_passchange control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbl_passchange As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txt_oldpass control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txt_oldpass As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txt_newpass control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txt_newpass As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txt_confpassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txt_confpassword As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''btn_update control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btn_update As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''imgbtn_cancel control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgbtn_cancel As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
