'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3053
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace unirecruite

    Partial Public Class ClientInformation

        '''<summary>
        '''form1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

        '''<summary>
        '''lblMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''txtClientName control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtClientName As Global.System.Web.UI.WebControls.TextBox

        '''<summary>
        '''imgBtnSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgBtnSearch As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''imgBtnClear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgBtnClear As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''ImgBtnBack control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ImgBtnBack As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''imgBtnNewCentreRegistration control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgBtnNewCentreRegistration As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''DivGrid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DivGrid As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        '''<summary>
        '''lblrecords control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblrecords As Global.System.Web.UI.WebControls.Label

        '''<summary>
        '''DG_ClientDetail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DG_ClientDetail As Global.System.Web.UI.WebControls.DataGrid

        '''<summary>
        '''imgfirst control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgfirst As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''imgprev control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgprev As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''tblPagebuttons control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblPagebuttons As Global.System.Web.UI.HtmlControls.HtmlTable

        '''<summary>
        '''imgnext control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgnext As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''imglast control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imglast As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''ddlPages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlPages As Global.System.Web.UI.WebControls.DropDownList

        '''<summary>
        '''imgBtnEnable control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgBtnEnable As Global.System.Web.UI.WebControls.ImageButton

        '''<summary>
        '''imgBtnDisable control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgBtnDisable As Global.System.Web.UI.WebControls.ImageButton
    End Class
End Namespace
