'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CourseMaintenance
    
    '''<summary>
    '''lblMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlMainCourse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMainCourse As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlSectionDes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSectionDes As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlCourses control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCourses As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtTotalTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalTime As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''imgBtnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnSearch As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imgBtnClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnClear As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''ImgBtnBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImgBtnBack As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imgBtnNewCourseRegistration control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnNewCourseRegistration As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DivGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivGrid As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''PageSizeList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PageSizeList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''imgfirst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgfirst As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''imgprev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgprev As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''tblPagebuttons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblPagebuttons As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''imgnext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgnext As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''imglast control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imglast As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblrecords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblrecords As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DataGridCourseDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DataGridCourseDetails As Global.System.Web.UI.WebControls.DataGrid
    
    '''<summary>
    '''imgBtnEnable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnEnable As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imgBtnDisable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnDisable As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imgBtnDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnDelete As Global.System.Web.UI.WebControls.Button
End Class
