'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ExamCount
    
    '''<summary>
    '''lblMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlcourse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlcourse As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''sel_subjectid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents sel_subjectid As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''searchbtn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents searchbtn As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnClear As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''gridDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblcount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcount As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblrecords control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblrecords As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DataGrid2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DataGrid2 As Global.System.Web.UI.WebControls.DataGrid
    
    '''<summary>
    '''imgfirst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgfirst As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''imgprev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgprev As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''imgnext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgnext As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''imglast control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imglast As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''ddlPages control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPages As Global.System.Web.UI.WebControls.DropDownList
End Class
