'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace unirecruite
    
    Partial Public Class login
        
        '''<summary>
        '''txt_login control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txt_login As Global.System.Web.UI.HtmlControls.HtmlInputText
        
        '''<summary>
        '''txt_pwd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txt_pwd As Global.System.Web.UI.HtmlControls.HtmlInputPassword
        
        '''<summary>
        '''btn_login control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btn_login As Global.System.Web.UI.HtmlControls.HtmlInputSubmit
    End Class
End Namespace
