'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace unirecruite
    
    Partial Public Class register
        
        '''<summary>
        '''lblLegend control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblLegend As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''LblMsg1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LblMsg1 As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''cmb_usertype control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents cmb_usertype As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''txt_firstname control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txt_firstname As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txt_middlename control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txt_middlename As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txt_surname control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txt_surname As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''rblist_sex control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rblist_sex As Global.System.Web.UI.WebControls.RadioButtonList
        
        '''<summary>
        '''txt_dob control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txt_dob As Global.System.Web.UI.HtmlControls.HtmlInputText
        
        '''<summary>
        '''txt_email control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txt_email As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txt_phone control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txt_phone As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''txtperadd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtperadd As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''Uploader control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Uploader As Global.System.Web.UI.WebControls.FileUpload
        
        '''<summary>
        '''StudentImage control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents StudentImage As Global.System.Web.UI.WebControls.Image
        
        '''<summary>
        '''headrow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents headrow As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''contentrow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents contentrow As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''txt_login control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txt_login As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''lbl_password control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbl_password As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''txt_password control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txt_password As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''trChangePass control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trChangePass As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''lnk_chpass control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lnk_chpass As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''trpwd control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trpwd As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''lbl_confpassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lbl_confpassword As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''star control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents star As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''txt_confpassword control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txt_confpassword As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''div1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents div1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''trClassHead control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents trClassHead As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''div2 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents div2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''rollnumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents rollnumber As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''txtrollnumber control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtrollnumber As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''centerrow control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents centerrow As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''Labelcentre control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Labelcentre As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''ddlCenters control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlCenters As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''tablediv control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tablediv As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''tblResult control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblResult As Global.System.Web.UI.HtmlControls.HtmlTable
        
        '''<summary>
        '''img_saveexit control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents img_saveexit As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''img_update control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents img_update As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''imgClear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgClear As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnBack control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnBack As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''imgReset control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgReset As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
