'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace unirecruite
    
    Partial Public Class searchQuestion
        
        '''<summary>
        '''lblMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''sel_test_type control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sel_test_type As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''txt_question control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txt_question As Global.System.Web.UI.WebControls.TextBox
        
        '''<summary>
        '''ChkExactSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ChkExactSearch As Global.System.Web.UI.WebControls.CheckBox
        
        '''<summary>
        '''imgBtnSearch control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgBtnSearch As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''imgBtnClear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgBtnClear As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnBack control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnBack As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnNewQuestion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnNewQuestion As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnQuestion control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnQuestion As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''BtnRemove control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents BtnRemove As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''ExportQueAnsTF control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ExportQueAnsTF As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''ExportQA_Match control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ExportQA_Match As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''gridDiv control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gridDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''PageSizeList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PageSizeList As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''imgfirst control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgfirst As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''imgprev control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgprev As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''tblPagebuttons control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblPagebuttons As Global.System.Web.UI.HtmlControls.HtmlTable
        
        '''<summary>
        '''imgnext control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgnext As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''imglast control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imglast As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''LblRecCnt control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents LblRecCnt As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''DGData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DGData As Global.System.Web.UI.WebControls.DataGrid
        
        '''<summary>
        '''ddlPages control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlPages As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''imgBtnEnable control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgBtnEnable As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''imgBtnDisable control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgBtnDisable As Global.System.Web.UI.WebControls.Button
    End Class
End Namespace
