'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Namespace unirecruite
    
    Partial Public Class search
        
        '''<summary>
        '''ScriptManager1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager
        
        '''<summary>
        '''UpdatePanel1 control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel
        
        '''<summary>
        '''lblMsg control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''lblReocrds control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblReocrds As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''sel_subjectid control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents sel_subjectid As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''ddlcourse control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents ddlcourse As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''searchUser control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents searchUser As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''btnclear control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents btnclear As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''gridDiv control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents gridDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''PageSizeList control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents PageSizeList As Global.System.Web.UI.WebControls.DropDownList
        
        '''<summary>
        '''imgfirst control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgfirst As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''imgprev control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgprev As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''imgnext control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imgnext As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''imglast control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents imglast As Global.System.Web.UI.WebControls.LinkButton
        
        '''<summary>
        '''lblNum control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents lblNum As Global.System.Web.UI.WebControls.Label
        
        '''<summary>
        '''DGData control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents DGData As Global.System.Web.UI.WebControls.DataGrid
        
        '''<summary>
        '''tblExam control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents tblExam As Global.System.Web.UI.HtmlControls.HtmlGenericControl
        
        '''<summary>
        '''txtExamDate control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents txtExamDate As Global.System.Web.UI.HtmlControls.HtmlInputText
        
        '''<summary>
        '''Mail control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents Mail As Global.System.Web.UI.WebControls.Button
        
        '''<summary>
        '''summarycont control.
        '''</summary>
        '''<remarks>
        '''Auto-generated field.
        '''To modify move field declaration from designer file to code-behind file.
        '''</remarks>
        Protected WithEvents summarycont As Global.System.Web.UI.WebControls.ValidationSummary
    End Class
End Namespace
