'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SubjectRegistration
    
    '''<summary>
    '''lblMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSubjectName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSubjectName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtSubCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSubCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''imgBtnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnSearch As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imgBtnClear control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnClear As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imgBtnBack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnBack As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imgBtnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnSubmit As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''chkrow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkrow As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''chkcourse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkcourse As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''maincourserow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents maincourserow As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''ddlMainCourse control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMainCourse As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''textboxcoderow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents textboxcoderow As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''txtcoursecode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcoursecode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''textboxrow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents textboxrow As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''txtTotalTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalTime As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''textMarksrow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents textMarksrow As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''txtTotalMarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTotalMarks As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''textPassmarksrow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents textPassmarksrow As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''txtPassMarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPassMarks As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''gridDiv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridDiv As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''PageSizeList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PageSizeList As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''imgfirst control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgfirst As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''imgprev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgprev As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''tblPagebuttons control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tblPagebuttons As Global.System.Web.UI.HtmlControls.HtmlTable
    
    '''<summary>
    '''imgnext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgnext As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''imglast control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imglast As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''LblTotalRecCnt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LblTotalRecCnt As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DataGridSubjectDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DataGridSubjectDetails As Global.System.Web.UI.WebControls.DataGrid
    
    '''<summary>
    '''imgBtnEnable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnEnable As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imgBtnDisable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnDisable As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''imgBtnDelete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgBtnDelete As Global.System.Web.UI.WebControls.Button
End Class
